FORMAT: X-1A

# Superdesk API

# Group users

## GET /users{/_id}
Returns a specific user by id.

+ Parameters
        + _id (required, string, `ab1`)

+ Response 200 (application/json)

    ```js
    {
        _id: "ab1", 
        _links: {
            self: {"href": "/user/1"}
        },
        _created: "2013-09-23T12:20:21Z",
        _updated: "2013-09-23T12:20:21Z",
        _permissions: {
            read: true,
            update: true
        },
        is_active: true,
        first_name: "karel",
        last_name: "badlik",
        display_name: "karel balik",
        username: "kbadlik",
        email: "kbadlik@gmail.com",
        user_info: {skype: "karel.badlik", phone: "+4207777777"}
    }
    ```

## GET /users
Returns a list of users.

+ Parameters
        + per_page `10` (optional, number, `10`)
        + page `1` (optional, number, `10`)

+ Response 200 (application/json)

    ```js
    {
        _links: {
            "self": {"href": "/users"},
            "next": {"href": "/users?page=2"}
        },
        _permissions: {
            read: true,
            create: true
        },
        _items: [
            {
                _links: {
                    "self": {"href": "/users/ab1"}
                },
                _created: "2012-12-12T10:34:15+0000",
                _updated: "2012-12-12T10:34:15+0000",
                is_active: true,
                first_name: 'karel',
                last_name: 'badlik',
                display_name: "karel badlik",
                username: "kbadlik",
                email: "kbadlik@gmail.com"
            },
            ...
        ]
    }
    ```

# Group items

## GET /items{/guid}

+ Response 200 (application/json)

    ```js
    {
        "guid": "urn:example.com:xyz",
        "version": 2,
        "provider": "example.com",
        "urgency": 4,
        "firstCreated": "2013-09-23T12:20:21Z",
        "versionCreated": "2013-09-23T12:30:05Z",
        "slugline" :"ITEM-SLUG",
        "headline": "News Item",
        "description": "News item info",
        "creditline": "EXAMPLE Images",
        "itemClass": "icls:text"
    }
    ```
