FORMAT: X-1A

# Superdesk API

# Group users

## GET /user/{id}
Returns a specific user by id.

+ Parameters
        + id (required, number, `1`)

+ Response 200

    ```js
    {
        _link_self: '/user/1',
        _create_time: '',
        _update_time: '',
        _is_active: true,
        _permissions: {
            read: true,
            update: true
        },
        first_name: 'karel',
        last_name: 'badlik',
        user_name: 'kbadlik',
        email: 'kbadlik@gmail.com',
        info: {skype: 'karel.badlik', phone: '+420 777 77 77'}
    }
    ```

## PUT /user/{id}
Updates a specific user.

+ Request

+ Response

## DELETE /user/{id}
Deletes a specific user.

+ Request

+ Response


## GET /user
Returns a list of users.

+ Parameters
        + per_page `10` (optional, number, `10`)
        + page `1` (optional, number, `10`)

+ Response 200

    ```js
    {
        _link: {
            self: '/user',
            previous: null,
            next: '/user?page=2',
        },
        _list: {
            item_total: 45,
            item_per_page: 10
            current_page: 1,
        }
        _permissions: {
            read: true,
            create: true
        },
        data: [
            {
                _link_self: '/user/1',
                _create_time: '',
                _update_time: '',
                _is_active: true,
                first_name: 'karel',
                last_name: 'badlik',
                user_name: 'kbadlik',
                email: 'kbadlik@gmail.com'
            },
            ...
        ]
    }
    ```

## POST /user
Creates a new user.

+ Request

+ Response

